version: '3'
services:
  web:
    env_file: ".env"
    image: the-potato-hamlet:dev
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../..:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEBUG: ${DEBUG}
  db:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
