all:
  children:
    docker_swarm:
      hosts:
        swarm_instance:
          ansible_host: "{{ lookup('env', 'TF_OUTPUT_instance_public_ip') }}"
  vars:
    ansible_user: ec2-user  # or ubuntu, depending on your AMI
    ansible_ssh_private_key_file: /path/to/your/key.pem
