---
- name: Setup Docker Swarm
  hosts: all
  become: yes
  vars:
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      become: true

    - name: Initialize Docker Swarm
      command: docker swarm init
      register: swarm_init
      changed_when: "'Swarm initialized' in swarm_init.stdout"

    - name: Get the join token for worker nodes
      command: docker swarm join-token worker -q
      register: worker_join_token
      when: swarm_init.changed

    - name: Output the worker join token
      debug:
        msg: "Worker join token: {{ worker_join_token.stdout }}"
      when: swarm_init.changed
