version: '3'
services:
  web:
    env_file: ".env"
    image: nyancoli/the-potato-hamlet:staging
    build:
      context: ../../
      dockerfile: ./docker/staging/Dockerfile
    ports:
      - "443:443"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DEBUG: ${DEBUG}
    secrets:
      - certfile
      - keyfile
  db:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

secrets:
  certfile:
    file: /etc/letsencrypt/live/koratata.com/fullchain.pem
  keyfile:
    file: /etc/letsencrypt/live/koratata.com/privkey.pem
