name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/staging/Dockerfile
          push: true
          tags: nyancoli/the-potato-hamlet:staging
      -
        name: Deploy to Docker Swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://ubuntu@koratata.com
          ssh_private_key: ${{ secrets.SWARM_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SWARM_SSH_PUBLIC_KEY }}
          args: stack deploy --compose-file /opt/docker/the_potato_hamlet/docker-compose-full.yml potato_hamlet
